[package]
name = "playotter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"
rand = "0.8.5"
rand_distr = "0.4.3"
rand_xorshift = "0.3.0"
